Repository NativeScript/theme, pull requests merged in 2019-11, with the labels that each got.

#216 fix(specificity): remove android specific font-size overrides
  src/scss/core/primitives/_headings.scss
Labels: bug, cla: yes

#221 fix(kendo): button colors in default and bootstrap skins are bro…
  package-lock.json
  package.json
  src/scss/core/colors/_dark.scss
Labels: cla: yes

#212 fix(styling): Remove border from non-editable TextViews
  CHANGELOG.md
  src/scss/mixins/components/_forms.scss
Labels: bug, cla: yes

#222 fix(bootstrap): Remove the second definition of $font-size, fix…
  src/scss/core/primitives/_text.scss
Labels: bug, cla: yes

#213 fix(styling): Fix ActionBar buttons background in modals
  src/scss/mixins/components/_action-bar.scss
Labels: bug, cla: yes

#224 feat(modal): add default styles for modals
  src/scss/core/primitives/_index.scss
  src/scss/mixins/_colorize.scss
Labels: cla: yes

#228 feat(modal): add default styles (#224)
  src/scss/core/primitives/_index.scss
  src/scss/mixins/_colorize.scss
Labels: cla: yes

#229 chore: release 2.2.1
  CHANGELOG.md
  package.json
  src/package.json
Labels: cla: yes

#226 chore: update deps and remove package-lock.json
  package-lock.json
  package.json
Labels: cla: yes

#227 chore(docs): Add Migration Guide
  MIGRATION-GUIDE.md
  README.md
  app/pages/forms.xml
  src/scss/mixins/_utilities.scss
  src/scss/mixins/components/_forms.scss
Labels: cla: yes, docs, enhancement

#225 fix(listview): Remove default ListView Image aspectFit
  src/scss/mixins/components/_list-view.scss
Labels: bug, cla: yes
