Repository NativeScript/theme, pull requests merged in 2019-10, with the labels that each got.

#189 feat: scoped package
  .travis.yml
  README.md
  app-compat/app.js
  app-compat/app.scss
  app-compat/pages/themes.js
  app/app.js
  app/app.scss
  app/bootstrap-based.scss
  app/customized.scss
  app/kendo-bootstrap.scss
  app/kendo-default.scss
  app/kendo-material.scss
  app/pages/themes.js
  package-lock.json
  package.json
  scripts/builder.js
  src/package.json
  webpack.config.js
Labels: cla: yes

#190 chore: bump version
  package.json
Labels: cla: yes

#191 fix(blue-skin): update accent color
  src/scss/variables/_blue.scss
Labels: cla: yes

#193 fix: stop importing view-common, use view instead
  src/index.js
Labels: cla: yes

#195 fix: change blue to nativescript blue
  src/scss/core/colors/_dark.scss
  src/scss/core/colors/_index.scss
  src/scss/variables/_blue.scss
  src/scss/variables/_index.scss
Labels: cla: yes

#196 fix: add more padding to action items
  src/scss/mixins/components/_action-bar.scss
Labels: cla: yes

#198 feat: add Frame control
  .gitignore
  src/scss/core/_controls.scss
  src/scss/mixins/components/_controls.scss
Labels: cla: yes

#199 Fix accents, separate default core styling
  app-compat/app.scss
  app-compat/customized.compat.scss
  app/app.scss
  app/customized.scss
  package-lock.json
  package.json
  src/_index.scss
  src/default.compat.scss
  src/default.scss
  src/scss/_controls.scss
  src/scss/core/_controls.scss
  src/scss/core/_utilities.scss
  src/scss/core/colors/_index.scss
  src/scss/core/primitives/_bootstrap.scss
  src/scss/mixins/components/_forms.scss
  src/scss/mixins/components/_list-view.scss
  src/scss/mixins/components/_side--drawer.scss
  src/scss/variables/_blue.scss
  src/scss/variables/_default.scss
  src/scss/variables/_grey.scss
  src/scss/variables/_index.scss
Labels: bug, cla: yes, enhancement

#200 feat: ship pre-parsed JSON files for all CSS
  scripts/builder.js
Labels: cla: yes

#201 Make the dark complementary color closer to the light one
  src/scss/core/colors/_dark.scss
Labels: bug, cla: yes, enhancement

#203 chore: update dependencies
  package.json
Labels: cla: yes

#205 Several fixes
  CHANGELOG.md
  README.md
  app/pages/tabs.js
  app/pages/tabs.xml
  package-lock.json
  package.json
  src/package.json
  src/scss/mixins/components/_controls.scss
  src/scss/mixins/components/_forms.scss
Labels: bug, cla: yes

#206 chore: unify issue templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: cla: yes
